/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ZtInputTags {
        "label": string;
        "type": string;
        "value": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLZtInputTagsElement extends Components.ZtInputTags, HTMLStencilElement {
    }
    var HTMLZtInputTagsElement: {
        prototype: HTMLZtInputTagsElement;
        new (): HTMLZtInputTagsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "zt-input-tags": HTMLZtInputTagsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ZtInputTags {
        "label"?: string;
        "onZtBlur"?: (event: CustomEvent<any>) => void;
        "onZtFocus"?: (event: CustomEvent<any>) => void;
        "onZtFocusIn"?: (event: CustomEvent<any>) => void;
        "onZtFocusOut"?: (event: CustomEvent<any>) => void;
        "onZtInputEmmiter"?: (event: CustomEvent<any>) => void;
        "type"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "zt-input-tags": ZtInputTags;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "zt-input-tags": LocalJSX.ZtInputTags & JSXBase.HTMLAttributes<HTMLZtInputTagsElement>;
        }
    }
}
